// ============================================================================
// Built-in demo data — no database required
// ============================================================================

// Simple ID generator
let _idCounter = 1000
export function generateId() {
  return 'id-' + (++_idCounter) + '-' + Math.random().toString(36).substr(2, 6)
}

// --------------------------------------------------------------------------
// Countries
// --------------------------------------------------------------------------
export const countries = [
  { code: 'AE', name: 'United Arab Emirates', region: 'gulf_states',    flag_emoji: '\u{1F1E6}\u{1F1EA}', lat: 23.4241,  lng: 53.8478 },
  { code: 'SA', name: 'Saudi Arabia',         region: 'gulf_states',    flag_emoji: '\u{1F1F8}\u{1F1E6}', lat: 23.8859,  lng: 45.0792 },
  { code: 'QA', name: 'Qatar',                region: 'gulf_states',    flag_emoji: '\u{1F1F6}\u{1F1E6}', lat: 25.3548,  lng: 51.1839 },
  { code: 'KW', name: 'Kuwait',               region: 'gulf_states',    flag_emoji: '\u{1F1F0}\u{1F1FC}', lat: 29.3117,  lng: 47.4818 },
  { code: 'BH', name: 'Bahrain',              region: 'gulf_states',    flag_emoji: '\u{1F1E7}\u{1F1ED}', lat: 26.0667,  lng: 50.5577 },
  { code: 'OM', name: 'Oman',                 region: 'gulf_states',    flag_emoji: '\u{1F1F4}\u{1F1F2}', lat: 21.4735,  lng: 55.9754 },
  { code: 'BN', name: 'Brunei',               region: 'southeast_asia', flag_emoji: '\u{1F1E7}\u{1F1F3}', lat: 4.9431,   lng: 114.9425 },
  { code: 'SG', name: 'Singapore',            region: 'southeast_asia', flag_emoji: '\u{1F1F8}\u{1F1EC}', lat: 1.3521,   lng: 103.8198 },
  { code: 'MY', name: 'Malaysia',             region: 'southeast_asia', flag_emoji: '\u{1F1F2}\u{1F1FE}', lat: 4.2105,   lng: 101.9758 },
  { code: 'PH', name: 'Philippines',          region: 'southeast_asia', flag_emoji: '\u{1F1F5}\u{1F1ED}', lat: 12.8797,  lng: 121.7740 },
  { code: 'VN', name: 'Vietnam',              region: 'southeast_asia', flag_emoji: '\u{1F1FB}\u{1F1F3}', lat: 14.0583,  lng: 108.2772 },
  { code: 'ID', name: 'Indonesia',            region: 'southeast_asia', flag_emoji: '\u{1F1EE}\u{1F1E9}', lat: -0.7893,  lng: 113.9213 },
  { code: 'HK', name: 'Hong Kong',            region: 'east_asia',      flag_emoji: '\u{1F1ED}\u{1F1F0}', lat: 22.3193,  lng: 114.1694 },
  { code: 'KR', name: 'South Korea',          region: 'east_asia',      flag_emoji: '\u{1F1F0}\u{1F1F7}', lat: 35.9078,  lng: 127.7669 },
  { code: 'JP', name: 'Japan',                region: 'east_asia',      flag_emoji: '\u{1F1EF}\u{1F1F5}', lat: 36.2048,  lng: 138.2529 },
  { code: 'CN', name: 'China',                region: 'east_asia',      flag_emoji: '\u{1F1E8}\u{1F1F3}', lat: 35.8617,  lng: 104.1954 },
  { code: 'US', name: 'United States',        region: 'americas',       flag_emoji: '\u{1F1FA}\u{1F1F8}', lat: 37.0902,  lng: -95.7129 },
  { code: 'GB', name: 'United Kingdom',       region: 'europe',         flag_emoji: '\u{1F1EC}\u{1F1E7}', lat: 55.3781,  lng: -3.4360 },
  { code: 'DE', name: 'Germany',              region: 'europe',         flag_emoji: '\u{1F1E9}\u{1F1EA}', lat: 51.1657,  lng: 10.4515 },
  { code: 'FR', name: 'France',               region: 'europe',         flag_emoji: '\u{1F1EB}\u{1F1F7}', lat: 46.2276,  lng: 2.2137 },
  { code: 'IN', name: 'India',                region: 'other',          flag_emoji: '\u{1F1EE}\u{1F1F3}', lat: 20.5937,  lng: 78.9629 },
  { code: 'BR', name: 'Brazil',               region: 'americas',       flag_emoji: '\u{1F1E7}\u{1F1F7}', lat: -14.2350, lng: -51.9253 },
  { code: 'AU', name: 'Australia',            region: 'other',          flag_emoji: '\u{1F1E6}\u{1F1FA}', lat: -25.2744, lng: 133.7751 },
  { code: 'IL', name: 'Israel',               region: 'other',          flag_emoji: '\u{1F1EE}\u{1F1F1}', lat: 31.0461,  lng: 34.8516 },
  { code: 'TR', name: 'Turkey',               region: 'other',          flag_emoji: '\u{1F1F9}\u{1F1F7}', lat: 38.9637,  lng: 35.2433 },
  { code: 'NO', name: 'Norway',               region: 'europe',         flag_emoji: '\u{1F1F3}\u{1F1F4}', lat: 60.4720,  lng: 8.4689 },
]

// --------------------------------------------------------------------------
// Entities — SWFs
// --------------------------------------------------------------------------
export const entities = [
  // Gulf States SWFs
  { id: 'ent-kia',       name: 'KIA',            full_name: 'Kuwait Investment Authority',             type: 'swf', country_code: 'KW', founded_year: 1953, aum_billions: 969,  sector: 'Diversified',                           funding_source: 'Oil revenue',                     government_affiliation: 'Kuwait Ministry of Finance',                               risk_level: 'low', strategic_significance: 5, description: 'One of the oldest sovereign wealth funds in the world, managing Kuwait\'s oil revenues since 1953.', tags: ['oil-funded', 'diversified'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-adia',      name: 'ADIA',           full_name: 'Abu Dhabi Investment Authority',          type: 'swf', country_code: 'AE', founded_year: 1976, aum_billions: 993,  sector: 'Diversified',                           funding_source: 'Oil revenue',                     government_affiliation: 'Abu Dhabi ruling family',                                  risk_level: 'low', strategic_significance: 5, description: 'Abu Dhabi\'s flagship investment arm and one of the world\'s largest sovereign wealth funds.', tags: ['oil-funded', 'mega-fund'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-adq',       name: 'ADQ',            full_name: 'ADQ',                                    type: 'swf', country_code: 'AE', founded_year: 2018, aum_billions: 157,  sector: 'Infrastructure/Energy/Healthcare',       funding_source: 'Government capital',              government_affiliation: 'Abu Dhabi government',                                     risk_level: 'low', strategic_significance: 4, description: 'Abu Dhabi holding company focused on transforming key sectors of the UAE economy.', tags: ['infrastructure', 'healthcare'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-mubadala',  name: 'Mubadala',       full_name: 'Mubadala Investment Company',             type: 'swf', country_code: 'AE', founded_year: 2002, aum_billions: 302,  sector: 'Technology/Energy/Aerospace',            funding_source: 'Government capital',              government_affiliation: 'Abu Dhabi government',                                     risk_level: 'low', strategic_significance: 5, description: 'Global investment company deploying capital across six continents in diverse sectors.', tags: ['technology', 'aerospace', 'energy'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-icd',       name: 'ICD',            full_name: 'Investment Corporation of Dubai',         type: 'swf', country_code: 'AE', founded_year: 2006, aum_billions: 340,  sector: 'Diversified',                           funding_source: 'Government capital',              government_affiliation: 'Dubai ruling family',                                      risk_level: 'low', strategic_significance: 5, description: 'Dubai\'s principal investment arm overseeing a diverse portfolio of government-owned entities.', tags: ['diversified', 'dubai'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-eia',       name: 'EIA',            full_name: 'Emirates Investment Authority',           type: 'swf', country_code: 'AE', founded_year: 2007, aum_billions: 87,   sector: 'Diversified',                           funding_source: 'Federal reserves',                government_affiliation: 'UAE federal government',                                   risk_level: 'low', strategic_significance: 3, description: 'Federal sovereign wealth fund of the UAE.', tags: ['federal', 'diversified'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-mumtalakat', name: 'Mumtalakat',    full_name: 'Bahrain Mumtalakat Holding Company',      type: 'swf', country_code: 'BH', founded_year: 2006, aum_billions: 18,   sector: 'Diversified',                           funding_source: 'Government capital',              government_affiliation: 'Kingdom of Bahrain',                                       risk_level: 'low', strategic_significance: 2, description: 'Bahrain\'s sovereign wealth fund managing strategic national assets.', tags: ['diversified'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-pif',       name: 'PIF',            full_name: 'Public Investment Fund',                  type: 'swf', country_code: 'SA', founded_year: 1971, aum_billions: 930,  sector: 'Diversified',                           funding_source: 'Oil revenue / Government capital', government_affiliation: 'Crown Prince / Council of Economic and Development Affairs', risk_level: 'low', strategic_significance: 5, description: 'Saudi Arabia\'s primary investment vehicle and a key driver of Vision 2030 economic diversification.', tags: ['vision-2030', 'mega-fund', 'oil-funded'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-sanabil',   name: 'Sanabil',        full_name: 'Sanabil Investments',                     type: 'swf', country_code: 'SA', founded_year: 2009, aum_billions: 72,   sector: 'Technology/Venture Capital',             funding_source: 'PIF allocation',                  government_affiliation: 'PIF subsidiary / Saudi government',                        risk_level: 'low', strategic_significance: 3, description: 'Technology-focused investment arm of PIF, investing in global venture capital and growth companies.', tags: ['tech', 'venture-capital'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-qia',       name: 'QIA',            full_name: 'Qatar Investment Authority',              type: 'swf', country_code: 'QA', founded_year: 2005, aum_billions: 510,  sector: 'Diversified',                           funding_source: 'Oil and gas revenue',             government_affiliation: 'Qatar ruling family',                                      risk_level: 'low', strategic_significance: 5, description: 'Qatar\'s sovereign wealth fund with major holdings in global real estate, banking, and luxury brands.', tags: ['oil-funded', 'diversified', 'global'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-oia',       name: 'OIA',            full_name: 'Oman Investment Authority',               type: 'swf', country_code: 'OM', founded_year: 2020, aum_billions: 42,   sector: 'Diversified',                           funding_source: 'Oil revenue / Government capital', government_affiliation: 'Sultanate of Oman',                                       risk_level: 'low', strategic_significance: 3, description: 'Oman\'s unified sovereign wealth fund managing the country\'s investment portfolio.', tags: ['diversified'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },

  // East Asia SWFs
  { id: 'ent-hkma',      name: 'HKMA LTGP',     full_name: 'HKMA Long-Term Growth Portfolio',         type: 'swf', country_code: 'HK', founded_year: 2009, aum_billions: 52,   sector: 'Long-term growth / PE',                 funding_source: 'Foreign exchange reserves',       government_affiliation: 'Hong Kong Monetary Authority',                             risk_level: 'low', strategic_significance: 3, description: 'Hong Kong Monetary Authority\'s portfolio focused on long-term growth opportunities.', tags: ['fx-reserves'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-hkgp',      name: 'HK Growth Portfolio', full_name: 'Hong Kong Growth Portfolio',         type: 'swf', country_code: 'HK', founded_year: 2022, aum_billions: 4,    sector: 'Strategic industries / Tech',            funding_source: 'Government capital',              government_affiliation: 'Hong Kong SAR Government',                                 risk_level: 'low', strategic_significance: 2, description: 'New Hong Kong government fund focused on strategic technology investments.', tags: ['tech', 'new-fund'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-kvic',      name: 'KVIC',           full_name: 'Korea Venture Investment Corporation',    type: 'swf', country_code: 'KR', founded_year: 2004, aum_billions: 12,   sector: 'Venture Capital / Startups',             funding_source: 'Government capital',              government_affiliation: 'Korean Ministry of SMEs and Startups',                     risk_level: 'low', strategic_significance: 3, description: 'Korea\'s public venture capital institution fostering startup ecosystem growth.', tags: ['venture-capital', 'startups'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-jic',       name: 'JIC',            full_name: 'Japan Investment Corporation',            type: 'swf', country_code: 'JP', founded_year: 2022, aum_billions: 22,   sector: 'Industry consolidation / Strategic sectors', funding_source: 'Government capital',          government_affiliation: 'Japanese government',                                      risk_level: 'low', strategic_significance: 3, description: 'Japan\'s newest investment institution focused on industry consolidation and competitiveness.', tags: ['industry', 'new-fund'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },

  // Southeast Asia SWFs
  { id: 'ent-temasek',   name: 'Temasek',        full_name: 'Temasek Holdings',                       type: 'swf', country_code: 'SG', founded_year: 1974, aum_billions: 389,  sector: 'Diversified',                           funding_source: 'Government capital',              government_affiliation: 'Government of Singapore / Ministry of Finance',            risk_level: 'low', strategic_significance: 5, description: 'Singapore\'s global investment company with a portfolio spanning technology, financial services, and life sciences.', tags: ['diversified', 'technology', 'global'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-gic',       name: 'GIC',            full_name: 'GIC Private Limited',                    type: 'swf', country_code: 'SG', founded_year: 1981, aum_billions: 770,  sector: 'Diversified',                           funding_source: 'Foreign exchange reserves',       government_affiliation: 'Government of Singapore',                                  risk_level: 'low', strategic_significance: 5, description: 'Singapore\'s reserve management company investing globally to preserve and enhance purchasing power.', tags: ['fx-reserves', 'mega-fund', 'global'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-khazanah',  name: 'Khazanah',       full_name: 'Khazanah Nasional Berhad',               type: 'swf', country_code: 'MY', founded_year: 1993, aum_billions: 35,   sector: 'Strategic industries / GLCs',            funding_source: 'Government capital',              government_affiliation: 'Malaysian government',                                     risk_level: 'low', strategic_significance: 3, description: 'Malaysia\'s sovereign wealth fund managing strategic national investments.', tags: ['strategic', 'glcs'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-bia',       name: 'BIA',            full_name: 'Brunei Investment Agency',                type: 'swf', country_code: 'BN', founded_year: 1983, aum_billions: 60,   sector: 'Diversified',                           funding_source: 'Oil and gas revenue',             government_affiliation: 'Sultan of Brunei / Ministry of Finance',                   risk_level: 'low', strategic_significance: 3, description: 'Brunei\'s primary investment vehicle for managing national oil wealth.', tags: ['oil-funded'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-mif',       name: 'MIF',            full_name: 'Maharlika Investment Fund',               type: 'swf', country_code: 'PH', founded_year: 2023, aum_billions: 3,    sector: 'Infrastructure/Strategic sectors',       funding_source: 'Government capital',              government_affiliation: 'Philippine government',                                    risk_level: 'low', strategic_significance: 2, description: 'The Philippines\' first sovereign wealth fund focused on infrastructure development.', tags: ['infrastructure', 'new-fund'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-scic',      name: 'SCIC',           full_name: 'State Capital Investment Corporation',    type: 'swf', country_code: 'VN', founded_year: 2005, aum_billions: 8,    sector: 'State enterprise management',            funding_source: 'State enterprise dividends',      government_affiliation: 'Vietnamese government / Ministry of Finance',               risk_level: 'low', strategic_significance: 2, description: 'Vietnam\'s sovereign investment arm managing state capital in key enterprises.', tags: ['state-enterprises'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'ent-ina',       name: 'INA',            full_name: 'Indonesia Investment Authority',          type: 'swf', country_code: 'ID', founded_year: 2021, aum_billions: 6,    sector: 'Infrastructure/Healthcare/Tech',         funding_source: 'Government capital',              government_affiliation: 'Indonesian government',                                    risk_level: 'low', strategic_significance: 2, description: 'Indonesia\'s sovereign wealth fund catalyzing investment in national development priorities.', tags: ['infrastructure', 'new-fund'], publicly_traded: false, stock_ticker: null, revenue_billions: null, employee_count: null, website: null, created_at: '2024-01-15T00:00:00Z' },

  // National Champions
  { id: 'ent-aramco',    name: 'Saudi Aramco',   full_name: 'Saudi Arabian Oil Company',               type: 'national_champion', country_code: 'SA', founded_year: 1933, aum_billions: null, sector: 'Oil & Gas',             funding_source: null, government_affiliation: 'PIF / Saudi government (98% ownership)', risk_level: 'medium', strategic_significance: 5, description: 'The world\'s largest oil producer and most profitable company.', tags: ['energy', 'mega-cap'], publicly_traded: true, stock_ticker: '2222.SR', revenue_billions: 535, employee_count: 70000, website: null, created_at: '2024-01-20T00:00:00Z' },
  { id: 'ent-sabic',     name: 'SABIC',          full_name: 'Saudi Basic Industries Corporation',      type: 'national_champion', country_code: 'SA', founded_year: 1976, aum_billions: null, sector: 'Chemicals',             funding_source: null, government_affiliation: 'Saudi Aramco (70% ownership)',       risk_level: 'low',    strategic_significance: 4, description: 'One of the world\'s largest diversified chemical companies.', tags: ['chemicals', 'materials'], publicly_traded: true, stock_ticker: '2010.SR', revenue_billions: 42, employee_count: 32000, website: null, created_at: '2024-01-20T00:00:00Z' },
  { id: 'ent-stc',       name: 'STC',            full_name: 'Saudi Telecom Company',                   type: 'national_champion', country_code: 'SA', founded_year: 1998, aum_billions: null, sector: 'Telecommunications',    funding_source: null, government_affiliation: 'PIF (64% ownership)',                risk_level: 'low',    strategic_significance: 3, description: 'Saudi Arabia\'s largest telecommunications company.', tags: ['telecom', 'digital'], publicly_traded: true, stock_ticker: '7010.SR', revenue_billions: 17, employee_count: 22000, website: null, created_at: '2024-01-20T00:00:00Z' },
  { id: 'ent-etisalat',  name: 'e&',             full_name: 'Emirates Telecommunications Group',       type: 'national_champion', country_code: 'AE', founded_year: 1976, aum_billions: null, sector: 'Telecommunications',    funding_source: null, government_affiliation: 'Emirates Investment Authority (60%)', risk_level: 'low',    strategic_significance: 4, description: 'UAE\'s largest telecom group with operations across the Middle East, Asia, and Africa.', tags: ['telecom', 'global'], publicly_traded: true, stock_ticker: 'ETISALAT.AD', revenue_billions: 14, employee_count: 42000, website: null, created_at: '2024-01-20T00:00:00Z' },
  { id: 'ent-dp-world',  name: 'DP World',       full_name: 'DP World Limited',                        type: 'national_champion', country_code: 'AE', founded_year: 2005, aum_billions: null, sector: 'Logistics/Ports',       funding_source: null, government_affiliation: 'Dubai government (ICD)',             risk_level: 'medium', strategic_significance: 5, description: 'Global port operator and supply chain solutions provider managing ports on six continents.', tags: ['logistics', 'infrastructure', 'global'], publicly_traded: false, stock_ticker: null, revenue_billions: 18, employee_count: 103000, website: null, created_at: '2024-01-20T00:00:00Z' },
  { id: 'ent-singtel',   name: 'Singtel',        full_name: 'Singapore Telecommunications Limited',    type: 'national_champion', country_code: 'SG', founded_year: 1879, aum_billions: null, sector: 'Telecommunications',    funding_source: null, government_affiliation: 'Temasek Holdings (52%)',             risk_level: 'low',    strategic_significance: 3, description: 'Southeast Asia\'s largest telecommunications company by market capitalization.', tags: ['telecom', 'regional'], publicly_traded: true, stock_ticker: 'Z74.SI', revenue_billions: 11, employee_count: 22000, website: null, created_at: '2024-01-20T00:00:00Z' },
]

// --------------------------------------------------------------------------
// Investments
// --------------------------------------------------------------------------
export const investments = [
  { id: 'inv-001', investor_entity_id: 'ent-pif',      target_name: 'Lucid Motors',           target_sector: 'Electric Vehicles',    deal_type: 'minority_stake',    status: 'completed',  amount_millions: 3400,  stake_percentage: 62,   announced_date: '2018-09-17', description: 'Strategic investment in luxury EV manufacturer aligned with Vision 2030.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-002', investor_entity_id: 'ent-pif',      target_name: 'NEOM',                   target_sector: 'Real Estate',          deal_type: 'infrastructure',    status: 'pending',    amount_millions: 500000, stake_percentage: 100,  announced_date: '2021-01-10', description: 'The mega-city development on the Red Sea coast as centerpiece of Saudi transformation.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-003', investor_entity_id: 'ent-adia',     target_name: 'Gatwick Airport',        target_sector: 'Infrastructure',       deal_type: 'acquisition',       status: 'completed',  amount_millions: 2800,  stake_percentage: 37,   announced_date: '2023-03-15', description: 'Stake in UK\'s second-largest airport.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-004', investor_entity_id: 'ent-qia',      target_name: 'Harrods',                target_sector: 'Retail/Luxury',        deal_type: 'acquisition',       status: 'completed',  amount_millions: 1500,  stake_percentage: 100,  announced_date: '2010-05-08', description: 'Full acquisition of iconic London department store.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-005', investor_entity_id: 'ent-qia',      target_name: 'Volkswagen',             target_sector: 'Automotive',           deal_type: 'minority_stake',    status: 'completed',  amount_millions: 9000,  stake_percentage: 17,   announced_date: '2009-06-01', description: 'Long-term strategic stake in German automaker.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-006', investor_entity_id: 'ent-temasek',  target_name: 'Ant Group',              target_sector: 'Fintech',              deal_type: 'venture_capital',   status: 'completed',  amount_millions: 1200,  stake_percentage: 2,    announced_date: '2018-06-20', description: 'Investment in China\'s largest fintech company pre-IPO.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-007', investor_entity_id: 'ent-gic',      target_name: 'Equinix',                target_sector: 'Data Centers',         deal_type: 'joint_venture',     status: 'completed',  amount_millions: 3900,  stake_percentage: null, announced_date: '2023-07-11', description: 'Data center joint venture for Asian market expansion.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-008', investor_entity_id: 'ent-mubadala', target_name: 'GlobalFoundries',        target_sector: 'Semiconductors',       deal_type: 'acquisition',       status: 'completed',  amount_millions: 2100,  stake_percentage: 85,   announced_date: '2009-03-02', description: 'Major stake in global semiconductor foundry.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-009', investor_entity_id: 'ent-kia',      target_name: 'Mercedes-Benz Group',    target_sector: 'Automotive',           deal_type: 'minority_stake',    status: 'completed',  amount_millions: 4200,  stake_percentage: 7,    announced_date: '2022-11-30', description: 'Strategic stake in German luxury automaker.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-010', investor_entity_id: 'ent-pif',      target_name: 'Jio Platforms',          target_sector: 'Technology/Telecom',   deal_type: 'minority_stake',    status: 'completed',  amount_millions: 1500,  stake_percentage: 2.3,  announced_date: '2020-06-18', description: 'Investment in India\'s largest digital services platform.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-011', investor_entity_id: 'ent-icd',      target_name: 'Emirates Airlines',      target_sector: 'Aviation',             deal_type: 'acquisition',       status: 'completed',  amount_millions: null,  stake_percentage: 100,  announced_date: '2006-07-01', description: 'Full ownership of Dubai\'s flagship carrier.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-012', investor_entity_id: 'ent-khazanah', target_name: 'IHH Healthcare',         target_sector: 'Healthcare',           deal_type: 'minority_stake',    status: 'completed',  amount_millions: 1800,  stake_percentage: 26,   announced_date: '2018-08-20', description: 'Stake in Asia\'s largest private healthcare group.', source_url: null, created_at: '2024-01-15T00:00:00Z' },
  { id: 'inv-013', investor_entity_id: 'ent-temasek',  target_name: 'OpenAI',                 target_sector: 'Artificial Intelligence', deal_type: 'venture_capital', status: 'rumored',    amount_millions: 500,   stake_percentage: null, announced_date: '2024-12-01', description: 'Reported interest in leading AI company.', source_url: null, created_at: '2024-12-01T00:00:00Z' },
  { id: 'inv-014', investor_entity_id: 'ent-adia',     target_name: 'Apollo Global Management', target_sector: 'Financial Services', deal_type: 'minority_stake',    status: 'completed',  amount_millions: 2500,  stake_percentage: 5,    announced_date: '2024-03-10', description: 'Strategic partnership with leading alternative asset manager.', source_url: null, created_at: '2024-03-10T00:00:00Z' },
]

// --------------------------------------------------------------------------
// Events
// --------------------------------------------------------------------------
export const events = [
  { id: 'evt-001', entity_id: 'ent-pif',      title: 'PIF announces $40B AI investment plan',                     description: 'Saudi Arabia\'s PIF commits to $40 billion in artificial intelligence infrastructure over the next five years.',                event_type: 'deal',              event_date: '2025-02-15', significance: 5, source_url: null, source_name: 'Reuters', created_at: '2025-02-15T00:00:00Z' },
  { id: 'evt-002', entity_id: 'ent-adia',     title: 'ADIA restructures Asian investment division',               description: 'Reorganization of ADIA\'s Asia-Pacific investment teams to better capture emerging opportunities.',                            event_type: 'leadership_change', event_date: '2025-01-20', significance: 3, source_url: null, source_name: 'Financial Times', created_at: '2025-01-20T00:00:00Z' },
  { id: 'evt-003', entity_id: 'ent-qia',      title: 'QIA increases European real estate allocation',             description: 'Qatar Investment Authority expands European property portfolio with new office and logistics acquisitions.',                    event_type: 'deal',              event_date: '2025-01-10', significance: 4, source_url: null, source_name: 'Bloomberg', created_at: '2025-01-10T00:00:00Z' },
  { id: 'evt-004', entity_id: 'ent-temasek',  title: 'Temasek reports record portfolio value',                    description: 'Singapore\'s Temasek Holdings reports net portfolio value of S$389 billion, driven by technology holdings.',                   event_type: 'earnings',          event_date: '2024-07-09', significance: 4, source_url: null, source_name: 'Straits Times', created_at: '2024-07-09T00:00:00Z' },
  { id: 'evt-005', entity_id: 'ent-gic',      title: 'GIC opens new office in São Paulo',                        description: 'GIC expands Latin American presence with a new office in Brazil.',                                                              event_type: 'news',              event_date: '2024-09-05', significance: 3, source_url: null, source_name: 'Bloomberg', created_at: '2024-09-05T00:00:00Z' },
  { id: 'evt-006', entity_id: 'ent-mubadala', title: 'Mubadala enters hydrogen partnership',                     description: 'Mubadala announces green hydrogen joint venture with European energy partners.',                                                event_type: 'deal',              event_date: '2024-11-18', significance: 4, source_url: null, source_name: 'Reuters', created_at: '2024-11-18T00:00:00Z' },
  { id: 'evt-007', entity_id: 'ent-kia',      title: 'KIA reports 8% annual return',                             description: 'Kuwait Investment Authority publishes annual results showing strong performance across asset classes.',                          event_type: 'earnings',          event_date: '2024-06-15', significance: 3, source_url: null, source_name: 'Kuwait Times', created_at: '2024-06-15T00:00:00Z' },
  { id: 'evt-008', entity_id: 'ent-pif',      title: 'PIF launches new mining company Manara',                   description: 'Saudi PIF establishes Manara Minerals to invest in global mining assets alongside Ma\'aden.',                                  event_type: 'deal',              event_date: '2024-01-11', significance: 5, source_url: null, source_name: 'Arab News', created_at: '2024-01-11T00:00:00Z' },
  { id: 'evt-009', entity_id: 'ent-icd',      title: 'ICD issues $1.5B green bond',                              description: 'Investment Corporation of Dubai debuts green sukuk to fund sustainable projects.',                                               event_type: 'deal',              event_date: '2024-04-22', significance: 3, source_url: null, source_name: 'Gulf News', created_at: '2024-04-22T00:00:00Z' },
  { id: 'evt-010', entity_id: 'ent-aramco',   title: 'Saudi Aramco reports record quarterly profit',              description: 'Aramco posts highest quarterly profit among listed companies globally.',                                                          event_type: 'earnings',          event_date: '2024-08-12', significance: 5, source_url: null, source_name: 'Reuters', created_at: '2024-08-12T00:00:00Z' },
  { id: 'evt-011', entity_id: 'ent-khazanah', title: 'Khazanah divests stake in Turkish hospital group',         description: 'Malaysia\'s Khazanah sells its stake in Turkish healthcare operations.',                                                        event_type: 'deal',              event_date: '2024-10-03', significance: 2, source_url: null, source_name: 'The Edge Malaysia', created_at: '2024-10-03T00:00:00Z' },
  { id: 'evt-012', entity_id: 'ent-adq',      title: 'ADQ acquires stake in Egyptian fertilizer company',        description: 'Abu Dhabi\'s ADQ expands into Egyptian agriculture sector with strategic acquisition.',                                         event_type: 'deal',              event_date: '2024-05-28', significance: 3, source_url: null, source_name: 'Bloomberg', created_at: '2024-05-28T00:00:00Z' },
  { id: 'evt-013', entity_id: null,            title: 'GCC sovereign funds surpass $4 trillion in combined AUM',  description: 'Milestone reached as Gulf Cooperation Council sovereign wealth funds collectively exceed $4 trillion.',                        event_type: 'news',              event_date: '2025-02-01', significance: 5, source_url: null, source_name: 'Sovereign Wealth Fund Institute', created_at: '2025-02-01T00:00:00Z' },
  { id: 'evt-014', entity_id: 'ent-dp-world', title: 'DP World expands port operations in Senegal',              description: 'DP World signs 25-year concession to develop and operate new container terminal.',                                               event_type: 'deal',              event_date: '2024-12-10', significance: 4, source_url: null, source_name: 'Seatrade Maritime', created_at: '2024-12-10T00:00:00Z' },
  { id: 'evt-015', entity_id: 'ent-ina',      title: 'INA signs co-investment MoU with ADIA',                    description: 'Indonesia Investment Authority deepens ties with Abu Dhabi Investment Authority for infrastructure co-investments.',             event_type: 'deal',              event_date: '2024-08-01', significance: 3, source_url: null, source_name: 'Jakarta Globe', created_at: '2024-08-01T00:00:00Z' },
]

// --------------------------------------------------------------------------
// Relationships
// --------------------------------------------------------------------------
export const relationships = [
  { id: 'rel-001', entity_a_id: 'ent-adia',    entity_b_id: 'ent-mubadala', relationship_type: 'government_link', description: 'Both Abu Dhabi sovereign entities under ruling family',                 strength: 4, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-002', entity_a_id: 'ent-adia',    entity_b_id: 'ent-adq',      relationship_type: 'government_link', description: 'Abu Dhabi sovereign entities',                                          strength: 3, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-003', entity_a_id: 'ent-adia',    entity_b_id: 'ent-eia',      relationship_type: 'government_link', description: 'UAE sovereign entities',                                                 strength: 2, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-004', entity_a_id: 'ent-mubadala', entity_b_id: 'ent-adq',     relationship_type: 'government_link', description: 'Abu Dhabi sovereign entities, overlapping mandates',                     strength: 3, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-005', entity_a_id: 'ent-icd',     entity_b_id: 'ent-eia',      relationship_type: 'government_link', description: 'UAE sovereign entities — Dubai and federal',                             strength: 2, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-006', entity_a_id: 'ent-pif',     entity_b_id: 'ent-sanabil',  relationship_type: 'subsidiary',      description: 'Sanabil operates as PIF subsidiary',                                    strength: 5, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-007', entity_a_id: 'ent-pif',     entity_b_id: 'ent-qia',      relationship_type: 'partner',         description: 'Multiple co-investment agreements',                                     strength: 3, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-008', entity_a_id: 'ent-temasek', entity_b_id: 'ent-gic',      relationship_type: 'government_link', description: 'Both Singapore sovereign entities under Ministry of Finance',           strength: 4, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-009', entity_a_id: 'ent-kia',     entity_b_id: 'ent-qia',      relationship_type: 'partner',         description: 'Gulf cooperation co-investments',                                       strength: 2, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-010', entity_a_id: 'ent-pif',     entity_b_id: 'ent-aramco',   relationship_type: 'investor',        description: 'PIF holds majority stake in Saudi Aramco',                              strength: 5, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-011', entity_a_id: 'ent-pif',     entity_b_id: 'ent-stc',      relationship_type: 'investor',        description: 'PIF is majority shareholder of STC',                                    strength: 4, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-012', entity_a_id: 'ent-eia',     entity_b_id: 'ent-etisalat', relationship_type: 'investor',        description: 'EIA is majority shareholder of e& (Etisalat)',                          strength: 4, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-013', entity_a_id: 'ent-icd',     entity_b_id: 'ent-dp-world', relationship_type: 'investor',        description: 'ICD controls DP World',                                                 strength: 5, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-014', entity_a_id: 'ent-temasek', entity_b_id: 'ent-singtel',  relationship_type: 'investor',        description: 'Temasek is majority shareholder of Singtel',                            strength: 4, created_at: '2024-01-15T00:00:00Z' },
  { id: 'rel-015', entity_a_id: 'ent-aramco',  entity_b_id: 'ent-sabic',    relationship_type: 'subsidiary',      description: 'Aramco owns 70% of SABIC',                                              strength: 5, created_at: '2024-01-15T00:00:00Z' },
]

// --------------------------------------------------------------------------
// Alerts & Notifications (demo)
// --------------------------------------------------------------------------
export const alerts = [
  { id: 'alert-001', user_id: 'demo-user', entity_id: 'ent-pif',     alert_type: 'new_investment', is_active: true, created_at: '2024-12-01T00:00:00Z' },
  { id: 'alert-002', user_id: 'demo-user', entity_id: 'ent-temasek', alert_type: 'news_mention',   is_active: true, created_at: '2024-12-01T00:00:00Z' },
  { id: 'alert-003', user_id: 'demo-user', entity_id: null,          alert_type: 'risk_change',    is_active: true, created_at: '2024-12-15T00:00:00Z' },
]

export const notifications = [
  { id: 'notif-001', user_id: 'demo-user', alert_id: 'alert-001', title: 'PIF announces $40B AI investment plan',           message: 'New major investment commitment detected.', is_read: false, created_at: '2025-02-15T10:00:00Z' },
  { id: 'notif-002', user_id: 'demo-user', alert_id: 'alert-002', title: 'Temasek reports record portfolio value',          message: 'Temasek portfolio reaches S$389 billion.',  is_read: true,  created_at: '2024-07-09T10:00:00Z' },
  { id: 'notif-003', user_id: 'demo-user', alert_id: 'alert-002', title: 'Temasek exploring OpenAI investment',             message: 'Reported interest in leading AI company.',  is_read: false, created_at: '2024-12-01T10:00:00Z' },
]
